[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
	autowp/autowp-mcp2515@^1.2.1
build_flags =
	-Wall

[env:megaatmega2560]

[env:megaatmega2560-16mhz]
build_flags =
	${env.build_flags}
	-D MCP_CRYSTAL_16MHZ

[env:sim]
build_flags =
	${env.build_flags}
	-D IOX_SIM
